### PR TITLE
fix issue #159

### PR DESCRIPTION
**Pull request by dmartin35**
Signed-off-by: David Martin <david@chaosiq.io>

### CODE REVIEW

**Comment by Lawouach** [comment]
is that an important one to have for next release @dmartin35?

**Comment by Lawouach** [comment]
hey @dmartin35 if you can rebase, I'll be happy to merge.

**Comment by dmartin35** [comment]
fixes #159

**Comment by dmartin35** [comment]
@Lawouach sorry for delay, this is now ready for merge

**Pull request merged**
